# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/wait4/source/repos/MCPPServerSoftware

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/wait4/source/repos/MCPPServerSoftware

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/wait4/source/repos/MCPPServerSoftware/CMakeFiles /mnt/c/Users/wait4/source/repos/MCPPServerSoftware//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/wait4/source/repos/MCPPServerSoftware/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MCPPServer

# Build rule for target.
MCPPServer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MCPPServer
.PHONY : MCPPServer

# fast build rule for target.
MCPPServer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServer.dir/build.make CMakeFiles/MCPPServer.dir/build
.PHONY : MCPPServer/fast

MCPPServerSoftware.o: MCPPServerSoftware.cpp.o
.PHONY : MCPPServerSoftware.o

# target to build an object file
MCPPServerSoftware.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServer.dir/build.make CMakeFiles/MCPPServer.dir/MCPPServerSoftware.cpp.o
.PHONY : MCPPServerSoftware.cpp.o

MCPPServerSoftware.i: MCPPServerSoftware.cpp.i
.PHONY : MCPPServerSoftware.i

# target to preprocess a source file
MCPPServerSoftware.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServer.dir/build.make CMakeFiles/MCPPServer.dir/MCPPServerSoftware.cpp.i
.PHONY : MCPPServerSoftware.cpp.i

MCPPServerSoftware.s: MCPPServerSoftware.cpp.s
.PHONY : MCPPServerSoftware.s

# target to generate assembly for a file
MCPPServerSoftware.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServer.dir/build.make CMakeFiles/MCPPServer.dir/MCPPServerSoftware.cpp.s
.PHONY : MCPPServerSoftware.cpp.s

io/configs.o: io/configs.cpp.o
.PHONY : io/configs.o

# target to build an object file
io/configs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServer.dir/build.make CMakeFiles/MCPPServer.dir/io/configs.cpp.o
.PHONY : io/configs.cpp.o

io/configs.i: io/configs.cpp.i
.PHONY : io/configs.i

# target to preprocess a source file
io/configs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServer.dir/build.make CMakeFiles/MCPPServer.dir/io/configs.cpp.i
.PHONY : io/configs.cpp.i

io/configs.s: io/configs.cpp.s
.PHONY : io/configs.s

# target to generate assembly for a file
io/configs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServer.dir/build.make CMakeFiles/MCPPServer.dir/io/configs.cpp.s
.PHONY : io/configs.cpp.s

io/json.o: io/json.cpp.o
.PHONY : io/json.o

# target to build an object file
io/json.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServer.dir/build.make CMakeFiles/MCPPServer.dir/io/json.cpp.o
.PHONY : io/json.cpp.o

io/json.i: io/json.cpp.i
.PHONY : io/json.i

# target to preprocess a source file
io/json.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServer.dir/build.make CMakeFiles/MCPPServer.dir/io/json.cpp.i
.PHONY : io/json.cpp.i

io/json.s: io/json.cpp.s
.PHONY : io/json.s

# target to generate assembly for a file
io/json.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServer.dir/build.make CMakeFiles/MCPPServer.dir/io/json.cpp.s
.PHONY : io/json.cpp.s

io/logger.o: io/logger.cpp.o
.PHONY : io/logger.o

# target to build an object file
io/logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServer.dir/build.make CMakeFiles/MCPPServer.dir/io/logger.cpp.o
.PHONY : io/logger.cpp.o

io/logger.i: io/logger.cpp.i
.PHONY : io/logger.i

# target to preprocess a source file
io/logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServer.dir/build.make CMakeFiles/MCPPServer.dir/io/logger.cpp.i
.PHONY : io/logger.cpp.i

io/logger.s: io/logger.cpp.s
.PHONY : io/logger.s

# target to generate assembly for a file
io/logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServer.dir/build.make CMakeFiles/MCPPServer.dir/io/logger.cpp.s
.PHONY : io/logger.cpp.s

networking/packets/packet.o: networking/packets/packet.cpp.o
.PHONY : networking/packets/packet.o

# target to build an object file
networking/packets/packet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServer.dir/build.make CMakeFiles/MCPPServer.dir/networking/packets/packet.cpp.o
.PHONY : networking/packets/packet.cpp.o

networking/packets/packet.i: networking/packets/packet.cpp.i
.PHONY : networking/packets/packet.i

# target to preprocess a source file
networking/packets/packet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServer.dir/build.make CMakeFiles/MCPPServer.dir/networking/packets/packet.cpp.i
.PHONY : networking/packets/packet.cpp.i

networking/packets/packet.s: networking/packets/packet.cpp.s
.PHONY : networking/packets/packet.s

# target to generate assembly for a file
networking/packets/packet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServer.dir/build.make CMakeFiles/MCPPServer.dir/networking/packets/packet.cpp.s
.PHONY : networking/packets/packet.cpp.s

server/client.o: server/client.cpp.o
.PHONY : server/client.o

# target to build an object file
server/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServer.dir/build.make CMakeFiles/MCPPServer.dir/server/client.cpp.o
.PHONY : server/client.cpp.o

server/client.i: server/client.cpp.i
.PHONY : server/client.i

# target to preprocess a source file
server/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServer.dir/build.make CMakeFiles/MCPPServer.dir/server/client.cpp.i
.PHONY : server/client.cpp.i

server/client.s: server/client.cpp.s
.PHONY : server/client.s

# target to generate assembly for a file
server/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServer.dir/build.make CMakeFiles/MCPPServer.dir/server/client.cpp.s
.PHONY : server/client.cpp.s

server/minecraft_server.o: server/minecraft_server.cpp.o
.PHONY : server/minecraft_server.o

# target to build an object file
server/minecraft_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServer.dir/build.make CMakeFiles/MCPPServer.dir/server/minecraft_server.cpp.o
.PHONY : server/minecraft_server.cpp.o

server/minecraft_server.i: server/minecraft_server.cpp.i
.PHONY : server/minecraft_server.i

# target to preprocess a source file
server/minecraft_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServer.dir/build.make CMakeFiles/MCPPServer.dir/server/minecraft_server.cpp.i
.PHONY : server/minecraft_server.cpp.i

server/minecraft_server.s: server/minecraft_server.cpp.s
.PHONY : server/minecraft_server.s

# target to generate assembly for a file
server/minecraft_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServer.dir/build.make CMakeFiles/MCPPServer.dir/server/minecraft_server.cpp.s
.PHONY : server/minecraft_server.cpp.s

threads/thread_pool.o: threads/thread_pool.cpp.o
.PHONY : threads/thread_pool.o

# target to build an object file
threads/thread_pool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServer.dir/build.make CMakeFiles/MCPPServer.dir/threads/thread_pool.cpp.o
.PHONY : threads/thread_pool.cpp.o

threads/thread_pool.i: threads/thread_pool.cpp.i
.PHONY : threads/thread_pool.i

# target to preprocess a source file
threads/thread_pool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServer.dir/build.make CMakeFiles/MCPPServer.dir/threads/thread_pool.cpp.i
.PHONY : threads/thread_pool.cpp.i

threads/thread_pool.s: threads/thread_pool.cpp.s
.PHONY : threads/thread_pool.s

# target to generate assembly for a file
threads/thread_pool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServer.dir/build.make CMakeFiles/MCPPServer.dir/threads/thread_pool.cpp.s
.PHONY : threads/thread_pool.cpp.s

util/component/text_components.o: util/component/text_components.cpp.o
.PHONY : util/component/text_components.o

# target to build an object file
util/component/text_components.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServer.dir/build.make CMakeFiles/MCPPServer.dir/util/component/text_components.cpp.o
.PHONY : util/component/text_components.cpp.o

util/component/text_components.i: util/component/text_components.cpp.i
.PHONY : util/component/text_components.i

# target to preprocess a source file
util/component/text_components.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServer.dir/build.make CMakeFiles/MCPPServer.dir/util/component/text_components.cpp.i
.PHONY : util/component/text_components.cpp.i

util/component/text_components.s: util/component/text_components.cpp.s
.PHONY : util/component/text_components.s

# target to generate assembly for a file
util/component/text_components.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCPPServer.dir/build.make CMakeFiles/MCPPServer.dir/util/component/text_components.cpp.s
.PHONY : util/component/text_components.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MCPPServer"
	@echo "... MCPPServerSoftware.o"
	@echo "... MCPPServerSoftware.i"
	@echo "... MCPPServerSoftware.s"
	@echo "... io/configs.o"
	@echo "... io/configs.i"
	@echo "... io/configs.s"
	@echo "... io/json.o"
	@echo "... io/json.i"
	@echo "... io/json.s"
	@echo "... io/logger.o"
	@echo "... io/logger.i"
	@echo "... io/logger.s"
	@echo "... networking/packets/packet.o"
	@echo "... networking/packets/packet.i"
	@echo "... networking/packets/packet.s"
	@echo "... server/client.o"
	@echo "... server/client.i"
	@echo "... server/client.s"
	@echo "... server/minecraft_server.o"
	@echo "... server/minecraft_server.i"
	@echo "... server/minecraft_server.s"
	@echo "... threads/thread_pool.o"
	@echo "... threads/thread_pool.i"
	@echo "... threads/thread_pool.s"
	@echo "... util/component/text_components.o"
	@echo "... util/component/text_components.i"
	@echo "... util/component/text_components.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

